### PR TITLE
Fixing dropped email messages due to character conversion error. OCEC…

### PR DESCRIPTION
**Pull request by venglisch**
…DR-4517
The character set for the HTML output is set to 'iso-8859-1'.  
Should this be changed to 'utf-8' with my change?

### CODE REVIEW

**Comment by bkline** [comment]
👍 on the switch to utf-8, though we should look at the code closely to see if we can figure out if there's a reason why we haven't switched already (I'm guessing worry about breaking code that's making assumptions about the default).

We generally don't merge changes into `master` until they've landed safely on PROD.

**Comment by venglisch** [comment]
> We generally don't merge changes into master until they've landed safely on PROD.

True, but I got your attention. :-)

**Comment by venglisch** [comment]
Looking through the code I believe the code was setting the charset to iso-8859-1 because it called sendMail().  You're detecting automatically in sendMailMime() which charset needs to be used.  For the purpose of the translation_jobs.py, however, we have to use the unicode encoding and therefore set the charset to utf-8.

**Comment by venglisch** [comment]
I made the utf-8 modifications and the tested changes are now on PROD.
Ready to merge into master.

**Comment by venglisch** [comment]
That's correct.  I was surprised myself and had to scratch my head a little because the encoding was set to the character set which wouldn't have worked properly.
Yes, I did test this change before and after it landed on PROD and it will create a nice big report on Monday.

**Pull request merged**
