### PR TITLE
Use the correct tool for sending non-ASCII email (OCECDR-4334)

### PR DESCRIPTION
**Pull request by venglisch**
This change is now on STAGE and PROD.  Ready to merge into master.

### CODE REVIEW

**Comment by venglisch** [comment]
I had a feeling you would like your work. :-)

**Comment by venglisch** [comment]
GitHub doesn't think so.  I was wondering why the merge is still blocked.

**Comment by venglisch** [comment]
Aller guten Dinge sind drei! :-)

**Comment by bkline** [comment]
Genau!

**Pull request merged**
